### ISSUE TITLE
emscripten-module-wrapper error

### ISSUE THREAD

**Issue by OR13** [transmute-industries/truebit-toolchain#1]
```
docker run --rm -e EMCC_WASM_BACKEND=1 -v $(pwd):/src truebit-toolchain:latest node /root/emcc-warmup/emscripten-module-wrapper/prepare.js ./src/reverse_alphabet.js --file ./src/alphabet.txt --file ./src/reverse_alphabet.txt --asmjs
exec:  cp [ './src/reverse_alphabet.wasm',
  '/tmp/emscripten-module-wrapper9ms0qs/./src/reverse_alphabet.wasm' ] /src
error  cp: cannot create regular file '/tmp/emscripten-module-wrapper9ms0qs/./src/reverse_alphabet.wasm': No such file or directory
 [ './src/reverse_alphabet.wasm',
  '/tmp/emscripten-module-wrapper9ms0qs/./src/reverse_alphabet.wasm' ]
{ _: [ './src/reverse_alphabet.js' ],
  file: [ './src/alphabet.txt', './src/reverse_alphabet.txt' ],
  asmjs: true }
{ _: [ './src/reverse_alphabet.js' ],
  file: [ './src/alphabet.txt', './src/reverse_alphabet.txt' ],
  asmjs: true,
  arg: [] }
exec:  cp [ './src/alphabet.txt',
  '/tmp/emscripten-module-wrapper9ms0qs/./src/alphabet.txt' ] /src
error  cp: cannot create regular file '/tmp/emscripten-module-wrapper9ms0qs/./src/alphabet.txt': No such file or directory
 [ './src/alphabet.txt',
  '/tmp/emscripten-module-wrapper9ms0qs/./src/alphabet.txt' ]
exec:  cp [ './src/reverse_alphabet.txt',
  '/tmp/emscripten-module-wrapper9ms0qs/./src/reverse_alphabet.txt' ] /src
error  cp: cannot create regular file '/tmp/emscripten-module-wrapper9ms0qs/./src/reverse_alphabet.txt': No such file or directory
 [ './src/reverse_alphabet.txt',
  '/tmp/emscripten-module-wrapper9ms0qs/./src/reverse_alphabet.txt' ]
exec:  /root/emcc-warmup/emscripten-module-wrapper/../ocaml-offchain/interpreter/wasm [ '-merge',
  './src/reverse_alphabet.wasm',
  '/root/emcc-warmup/emscripten-module-wrapper/filesystem.wasm' ] undefined
error  string:1.1-1.38: i/o error: ./src/reverse_alphabet.wasm: No such file or directory
 [ '-merge',
  './src/reverse_alphabet.wasm',
  '/root/emcc-warmup/emscripten-module-wrapper/filesystem.wasm' ]
exec:  /root/emcc-warmup/emscripten-module-wrapper/../ocaml-offchain/interpreter/wasm [ '-add-globals',
  '/root/emcc-warmup/emscripten-module-wrapper/globals-asmjs.json',
  'merge.wasm' ] undefined
error  string:1.1-1.21: i/o error: merge.wasm: No such file or directory
 [ '-add-globals',
  '/root/emcc-warmup/emscripten-module-wrapper/globals-asmjs.json',
  'merge.wasm' ]
exec:  /root/emcc-warmup/emscripten-module-wrapper/../ocaml-offchain/interpreter/wasm -m -input -table-size 20 -stack-size 20 -memory-size 25 -wasm globals.wasm -file ./src/alphabet.txt -file ./src/reverse_alphabet.txt -asmjs undefined
stderr: string:1.1-1.23: i/o error: globals.wasm: No such file or directory

child process exited with code 1
cd /tmp/emscripten-module-wrapper9ms0qs
Uploaded to IPFS  { path: 'globals.wasm',
  hash: 'QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn',
  size: 4 }
(node:1) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at processTask (/root/emcc-warmup/emscripten-module-wrapper/prepare.js:178:87)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by hswick** [comment]
This looks like filepath issues inside of the docker container

**Comment by OR13** [comment]
yep, after coming back to it, it looks like there are pathing issues with the temp dir...
